export const fakeMovies = [
  {
    _id: "12wew",
    title: "Terminator",
    numberInStock: 6,
    dailyRentalRate: 2.5,
    genre: { name: "Action", _id: "jhchjd" },
    liked: true,
  },
  {
    _id: "efueri",
    title: "Mulan",
    numberInStock: 3,
    dailyRentalRate: 4.5,
    genre: { name: "Adventure", _id: "gsvcgh" },
    liked: true,
  },
  {
    _id: "hdvg",
    title: "Rogue",
    numberInStock: 8,
    dailyRentalRate: 3.5,
    genre: { name: "Romance", _id: "vhhjc" },
    liked: true,
  },
  {
    _id: "fbhjf",
    title: "Bones",
    numberInStock: 18,
    dailyRentalRate: 3,
    genre: { name: "Animation", _id: "jbdc" },
    liked: false,
  },
  {
    _id: "vuvcsh",
    title: "Die Hard",
    numberInStock: 2,
    dailyRentalRate: 1,
    genre: { name: "Action", _id: "jhchjd" },
    liked: false,
  },
  {
    _id: "jjbus",
    title: "The Avengers",
    numberInStock: 16,
    dailyRentalRate: 3,
    genre: { name: "Action", _id: "jhchjd" },
    liked: false,
  },
  {
    _id: "des8",
    title: "Gone Girl",
    numberInStock: 13,
    dailyRentalRate: 3,
    genre: { name: "Thriller", _id: "jddfs" },
    liked: false,
  },
  {
    _id: "dfgs8",
    title: "Get Out",
    numberInStock: 21,
    dailyRentalRate: 1.3,
    genre: { name: "Thriller", _id: "jddfs" },
    liked: false,
  },
  {
    _id: "gbgfh",
    title: "Die Hard",
    numberInStock: 2,
    dailyRentalRate: 1,
    genre: { name: "Action", _id: "jhchjd" },
    liked: false,
  },
  {
    _id: "jbrfh",
    title: "The Avengers",
    numberInStock: 16,
    dailyRentalRate: 3,
    genre: { name: "Action", _id: "jhchjd" },
    liked: false,
  },
  {
    _id: "dndkjvn",
    title: "Gone Girl",
    numberInStock: 13,
    dailyRentalRate: 3,
    genre: { name: "Thriller", _id: "jddfs" },
    liked: false,
  },
  {
    _id: "djhd",
    title: "Get Out",
    numberInStock: 21,
    dailyRentalRate: 1.3,
    genre: { name: "Thriller", _id: "jddfs" },
    liked: false,
  },
];
